### ISSUE TITLE
Leverage dplyr dependency

### ISSUE THREAD

**Issue by billy34** [alvarofranq/eventr#1]
Hello

Nice work but maybe to widen its use for example for low level purpose you could leverage the `dplyr` dependency.

You use `dplyr` only in your examples not in your code (as far as I can see). I have nothing against `dplyr` for high level coding but it is an heavy dependency with lots of sub dependencies. 

It could be moved to `Suggests` instead of `Imports` section in `DESCRIPTION` file

**Comment by alvarofranq** [comment]
Done, thaks you for the comment
